export const EXPERIENCE_LIST = [
	{
		company: 'Loopio',
		branch: '(Software)',
		country: 'Burnaby, Canada (Remote)',
		job: 'Senior Software Developer',
		date: 'Nov 2024 — Present',
		responsibilities: [
			
		],
		techStack: [
		],
	},
	{
		company: 'Loopio',
		branch: '(Software)',
		country: 'Burnaby, Canada (Remote)',
		job: 'Software Developer (Level 3)',
		date: 'Oct 2023 — Oct 2024',
		responsibilities: [
			
		],
		techStack: [
		],
	},
	{
		company: 'Driveroo',
		branch: '(Automotive, Software)',
		country: 'Remote',
		job: 'Backend Developer',
		date: 'Mar 2023 — Oct 2023',
		responsibilities: [
			'Refactored modules with accumulated technical debt, resulting in a 40% improvement in performance and making future code maintenance and enhancements easier',
			'Supported the development of 10+ new features',
		],
		techStack: [
			'PHP',
			'Laravel',
			'PostgreSQL',
			'Redis',
			'Docker',
			'AWS',
			'Azure',
			'Git',
			'Nginx',
		],
	},
	{
		company: 'Itransition',
		branch: '(Software)',
		country: 'Kyiv, Ukraine',
		job: 'PHP Developer',
		date: 'Jul 2021 – Feb 2023',
		responsibilities: [
			'Performed project audit to assess its current state and effectiveness. Identified areas for improvement and provided a report with recommendations aimed at reducing development time by half',
			'Improved core module by refactoring the codebase and implementing an effective class structure which helped to eliminate code duplication in 3+ places',
		],
		techStack: [
			'PHP',
			'Laravel',
			'Symfony',
			'MySQL',
			'Redis',
			'Docker',
			'PHPUnit',
			'MongoDB',
			'Git',
			'Linux',
			'Nginx',
			'Apache',
		],
	},
	{
		company: 'Tallium',
		branch: '(Software)',
		country: 'Kyiv, Ukraine',
		job: 'Backend Developer',
		date: 'Sep 2019 – Jul 2021',
		responsibilities: [
			"Successfully brought the project to release being the only developer on it, having to design and develop server logic, build UI, set up server environment and CI/CD pipelines, set up performance monitoring tools, and discuss client's requirements translating them into technical specifications",
			'Designed and developed a project architecture and an API for a SaaS platform that allows customers to make appointments for the services of an entrepreneur with custom subscription logic for iOS and Android applications',
		],
		techStack: [
			'PHP',
			'Laravel',
			'Lumen',
			'PostgreSQL',
			'MySQL',
			'Redis',
			'PHPUnit',
			'JavaScript',
			'Vue.js',
			'HTML',
			'CSS',
			'Tailwind CSS',
			'Nuxt.js',
			'Node.js',
			'Docker',
			'AWS',
			'Google Cloud Platform',
			'Azure',
			'Git',
			'GitLab CI/CD',
			'Linux',
			'Nginx',
			'Apache',
		],
	},
	{
		company: 'Kvadrosoft',
		branch: '(Social Media)',
		country: 'Mariupol, Ukraine',
		job: 'Full Stack Developer',
		date: 'Nov 2017 – Jul 2019',
		responsibilities: [
			'Contributed to a high-loaded project serving over a million users, obtaining hands-on experience in working with replicated and sharded databases, including database query optimization',
			'Created an automated template for mass mailings that increased the speed of their creation by 10x, eliminating the need of involving content managers',
			'Introduced Bootstrap for use as a markup framework resulting in up to 2x faster frontend development',
		],
		techStack: [
			'PHP',
			'MySQL',
			'Memcached',
			'Sphinx',
			'Gearman',
			'JavaScript',
			'jQuery',
			'HTML',
			'CSS',
			'Git',
			'Linux',
			'Apache',
			'Nginx',
		],
	},
]
